export const SET_SELECTED_NAME = 'SET_SELECTED_NAME'
export const SET_CHILDREN_NAMES = 'SET_CHILDREN_NAMES'

export const UNSET_CHILDREN_NAMES = 'UNSET_CHILDREN_NAMES'
export const CLEAR_ALL_SELECTED_NAMES = 'CLEAR_ALL_SELECTED_NAMES'
